GET http://localhost:8080/film/maude
Accept: application/json

###
GET http://localhost:8080/film/maude
Accept: application/json

###
GET http://localhost:8080/rentals/australia
Accept: application/json

###
GET http://localhost:8080/rentals/canada/titulo/alice
Accept: application/json

###
POST http://localhost:8080/rentals
Content-Type: application/json

{
    "rentalDate":"2021-11-23 12:00:00",
    "customerId":7,
    "returnDate":"2021-11-23 12:00:00",
    "country":"australia",
    "lastUpdate":"2021-11-23 12:00:00",
    "paymentDate":"2021-11-23 12:00:00",
    "amount":2.2,
    "films":[
        1,
        2,
        3,
        4
    ]
}
//staff_id int (1 if Canada; 2 if Australia)